/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFrame.java
 *
 * Created on 8 Jul, 2012, 7:48:17 PM
 */

package calc;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.*;
import java.awt.Toolkit;



/**
 *
 * @author AJAY-PREM
 */
public class jFrame extends javax.swing.JFrame {

    String text=new String("");
    String text0=new String("");
    double val,op1,op2;
    boolean calflag=false,opflag=false,radflag=true;
    String op;
    /** Creates new form jFrame */
    public jFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(jFrame.class.getResource("calculator.png")));
    }

    private void set(){
        Font f=new Font("Arial",Font.BOLD,15);
    t1.setHorizontalAlignment(JTextField.RIGHT);
        t0.setHorizontalAlignment(JTextField.RIGHT);
        t1.setFont(f);
        t0.setFont(f);
        setSize(460,310);
        t0.setBackground(Color.WHITE);
            t1.setBackground(Color.WHITE);


    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bX2 = new javax.swing.JButton();
        bXY = new javax.swing.JButton();
        bX3 = new javax.swing.JButton();
        b10X = new javax.swing.JButton();
        bPi = new javax.swing.JButton();
        bTan = new javax.swing.JButton();
        bCos = new javax.swing.JButton();
        bSin = new javax.swing.JButton();
        bRut = new javax.swing.JButton();
        bPM = new javax.swing.JButton();
        bFac = new javax.swing.JButton();
        bInt = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bDec = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        bMin = new javax.swing.JButton();
        bDiv = new javax.swing.JButton();
        bMul = new javax.swing.JButton();
        bBSp = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        bMod = new javax.swing.JButton();
        bEq = new javax.swing.JButton();
        Radian = new javax.swing.JToggleButton();
        t0 = new javax.swing.JTextField();
        MemPlus = new javax.swing.JButton();
        MemMin = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        Standard = new javax.swing.JMenuItem();
        Scientific = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        Us = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        bX2.setText("x^2");
        bX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bX2ActionPerformed(evt);
            }
        });

        bXY.setText("x^y");
        bXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXYActionPerformed(evt);
            }
        });

        bX3.setText("x^3");
        bX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bX3ActionPerformed(evt);
            }
        });

        b10X.setText("10^x");
        b10X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10XActionPerformed(evt);
            }
        });

        bPi.setText("∏");
        bPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPiActionPerformed(evt);
            }
        });

        bTan.setText("tan");
        bTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTanActionPerformed(evt);
            }
        });

        bCos.setText("cos");
        bCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCosActionPerformed(evt);
            }
        });

        bSin.setText("sin");
        bSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSinActionPerformed(evt);
            }
        });

        bRut.setText("√");
        bRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRutActionPerformed(evt);
            }
        });

        bPM.setText("±");
        bPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPMActionPerformed(evt);
            }
        });

        bFac.setText("n!");
        bFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFacActionPerformed(evt);
            }
        });

        bInt.setText("Int");
        bInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIntActionPerformed(evt);
            }
        });

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        bDec.setText(".");
        bDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDecActionPerformed(evt);
            }
        });

        bAdd.setText("+");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bMin.setText("-");
        bMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinActionPerformed(evt);
            }
        });

        bDiv.setText("/");
        bDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivActionPerformed(evt);
            }
        });

        bMul.setText("*");
        bMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMulActionPerformed(evt);
            }
        });

        bBSp.setText("←");
        bBSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBSpActionPerformed(evt);
            }
        });

        t1.setEditable(false);

        bMod.setText("%");
        bMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModActionPerformed(evt);
            }
        });

        bEq.setText("=");
        bEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEqActionPerformed(evt);
            }
        });

        Radian.setText("Radian");
        Radian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadianActionPerformed(evt);
            }
        });

        t0.setEditable(false);
        t0.setDisabledTextColor(java.awt.Color.blue);
        t0.setSelectedTextColor(java.awt.Color.blue);

        MemPlus.setText("M+");
        MemPlus.setEnabled(false);
        MemPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemPlusActionPerformed(evt);
            }
        });

        MemMin.setText("M-");
        MemMin.setEnabled(false);
        MemMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemMinActionPerformed(evt);
            }
        });

        File.setText("File");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        Menu.add(File);

        View.setText("View");

        Standard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        Standard.setText("Standard");
        Standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardActionPerformed(evt);
            }
        });
        View.add(Standard);

        Scientific.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        Scientific.setText("Scientific");
        Scientific.setSelected(true);
        Scientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScientificActionPerformed(evt);
            }
        });
        View.add(Scientific);

        Menu.add(View);

        About.setText("About");

        Us.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        Us.setText("Who R We ??");
        Us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsActionPerformed(evt);
            }
        });
        About.add(Us);

        Help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        About.add(Help);

        Menu.add(About);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(t0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Radian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bXY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bX3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b10X))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bPi, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(bTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bSin, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MemPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b1)
                                    .addComponent(b7)
                                    .addComponent(b4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b8)
                                    .addComponent(b5)
                                    .addComponent(b2)))
                            .addComponent(b0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bDec))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bAdd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(bDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bMul, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bEq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(bMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(bBSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)))
                            .addComponent(MemMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t0, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radian)
                    .addComponent(MemPlus)
                    .addComponent(MemMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bX2)
                    .addComponent(bSin)
                    .addComponent(bPM)
                    .addComponent(b8)
                    .addComponent(b9)
                    .addComponent(bAdd)
                    .addComponent(bBSp)
                    .addComponent(b7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bXY)
                    .addComponent(bCos)
                    .addComponent(bFac)
                    .addComponent(b4)
                    .addComponent(b5)
                    .addComponent(b6)
                    .addComponent(bMin)
                    .addComponent(bMod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bX3)
                            .addComponent(bTan)
                            .addComponent(bRut)
                            .addComponent(b1)
                            .addComponent(b2)
                            .addComponent(b3)
                            .addComponent(bMul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b10X)
                            .addComponent(bPi)
                            .addComponent(bInt)
                            .addComponent(b0)
                            .addComponent(bDec)
                            .addComponent(bDiv)))
                    .addComponent(bEq, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bX2ActionPerformed
        text0="sqr("+t1.getText()+")";
        t0.setText(text0);
        val=Double.parseDouble(t1.getText());
        text=""+val*val;
        t1.setText(text);
        calflag=true;
}//GEN-LAST:event_bX2ActionPerformed

    private void bSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSinActionPerformed
        text0="sin("+t1.getText()+")";
        t0.setText(text0);
        val=Double.parseDouble(t1.getText());
        if(radflag)
            text=""+Math.sin(val);
        else
            text=""+Math.sin(Math.toRadians(val));
        t1.setText(text);
        calflag=true;
}//GEN-LAST:event_bSinActionPerformed

    private void bPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPMActionPerformed

        val=Double.parseDouble(t1.getText());
        text=""+(-1)*val;
        t1.setText(text);
        calflag=true;
}//GEN-LAST:event_bPMActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(opflag||calflag)
        {
            text="1";
            t1.setText(text);
            
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"1";
        t1.setText(text);
        }
}//GEN-LAST:event_b1ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(opflag||calflag)
        {
            text="7";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"7";
        t1.setText(text);
        }
}//GEN-LAST:event_b7ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(opflag||calflag)
        {
            text="4";
            t1.setText(text);
        if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"4";
        t1.setText(text);
        }
}//GEN-LAST:event_b4ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(opflag||calflag)
        {
            text="8";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"8";
        t1.setText(text);
        }
}//GEN-LAST:event_b8ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(opflag||calflag)
        {
            text="5";
            t1.setText(text);
                calflag=false;
                opflag=false;
            
        }
        else
        {
        text=text+"5";
        t1.setText(text);
        }
}//GEN-LAST:event_b5ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(opflag||calflag)
        {
            text="2";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"2";
        t1.setText(text);
        }
}//GEN-LAST:event_b2ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if(opflag||calflag)
        {
            text="0";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"0";
        t1.setText(text);
        }
}//GEN-LAST:event_b0ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(opflag||calflag)
        {
            text="3";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"3";
        t1.setText(text);
        }
}//GEN-LAST:event_b3ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(opflag||calflag)
        {
            text="9";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"9";
        t1.setText(text);
        }
}//GEN-LAST:event_b9ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(opflag||calflag)
        {
            text="6";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        text=text+"6";
        t1.setText(text);
        }
}//GEN-LAST:event_b6ActionPerformed

    private void bDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDecActionPerformed
        if(opflag||calflag)
        {
            text="0.";
            t1.setText(text);
            if(calflag)
                calflag=false;
            else
                opflag=false;
        }
        else
        {
        if(text.equals("")){
            text="0.";
            t1.setText(text);
        }
        else{
        text=text+".";
        t1.setText(text);
        }
        }

}//GEN-LAST:event_bDecActionPerformed

    private void bBSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBSpActionPerformed
        text=t1.getText();
        if(text.equals("")||calflag)
        {
            t1.setText("");
            t0.setText("");
        }
        else
        {
        text=text.substring(0,text.length()-1);
        t1.setText(text);
        }
}//GEN-LAST:event_bBSpActionPerformed

    private void bXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXYActionPerformed
       if(!opflag)
       {
           op1=Double.parseDouble(text);
           opflag=true;
           op="bXY";
           t1.setText("");
       }
    }//GEN-LAST:event_bXYActionPerformed

    private void bCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCosActionPerformed
         text0="cos("+t1.getText()+")";
        t0.setText(text0);
        val=Double.parseDouble(t1.getText());
        if(radflag)
        text=""+Math.cos(val);
        else
            text=""+Math.cos(Math.toRadians(val));
        t1.setText(text);
        calflag=true;
        
    }//GEN-LAST:event_bCosActionPerformed

    private void bTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTanActionPerformed
        text0="tan("+t1.getText()+")";
        t0.setText(text0);
        val=Double.parseDouble(t1.getText());
        if(radflag)
        text=""+Math.tan(val);
        else
            text=""+Math.tan(Math.toRadians(val));
        t1.setText(text);
        calflag=true;

    }//GEN-LAST:event_bTanActionPerformed

    private void b10XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10XActionPerformed
        val=Double.parseDouble(t1.getText());
        text0="10^"+val;
        t0.setText(text0);
        text=""+Math.pow(10,val);
        t1.setText(text);
        calflag=true;

    }//GEN-LAST:event_b10XActionPerformed

    private void bPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPiActionPerformed
    }//GEN-LAST:event_bPiActionPerformed

    private void bEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEqActionPerformed
        double result=0;
        t0.setText("");
        op2=Double.parseDouble(text);

        if(op.equals("bXY"))
        {
            text=""+Math.pow(op1,op2);
            t1.setText(text);
            
        }
        else if(op.equals("+"))
        {
            result=op1+op2;
            text=""+result;
            t1.setText(text);
        }
        else if(op.equals("-"))
        {
            result=op1-op2;
            text=""+result;
            t1.setText(text);
        }
        else if(op.equals("*"))
        {
            result=op1*op2;
            text=""+result;
            t1.setText(text);
        }
        else if(op.equals("/"))
        {
            result=op1/op2;
            text=""+result;
            t1.setText(text);
        }
        else if(op.equals("%"))
        {
            result=op1%op2;
            text=""+result;
            t1.setText(text);
        }
        calflag=true;
    }//GEN-LAST:event_bEqActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed

    }//GEN-LAST:event_FileActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
            System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void UsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsActionPerformed
        JOptionPane.showMessageDialog(rootPane,"This is © forward s/ash inc. Product");
    }//GEN-LAST:event_UsActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
            op1=Float.parseFloat(text);
            op=evt.getActionCommand();
            opflag=true;
            text0=""+op1+"+";
            t0.setText(text0);
            t1.setText("");
    }//GEN-LAST:event_bAddActionPerformed

    private void bMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinActionPerformed
            op1=Float.parseFloat(text);
            op=evt.getActionCommand();
            opflag=true;
            text0=""+op1+"-";
            t0.setText(text0);
            t1.setText("");

    }//GEN-LAST:event_bMinActionPerformed

    private void bMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMulActionPerformed
            op1=Float.parseFloat(text);
            op=evt.getActionCommand();
            opflag=true;
            text0=""+op1+"*";
            t0.setText(text0);
            t1.setText("");

    }//GEN-LAST:event_bMulActionPerformed

    private void bDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivActionPerformed
            op1=Float.parseFloat(text);
            op=evt.getActionCommand();
            opflag=true;
            text0=""+op1+"/";
            t0.setText(text0);
            t1.setText("");

    }//GEN-LAST:event_bDivActionPerformed

    private void bModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModActionPerformed
            op1=Float.parseFloat(text);
            op=evt.getActionCommand();
            opflag=true;
            text0="mod("+op1+")";
            t0.setText(text0);
            t1.setText("");

    }//GEN-LAST:event_bModActionPerformed

    private void bRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRutActionPerformed
            val=Double.parseDouble(t1.getText());
            text0="SuareRoot("+t1.getText()+")";
            t0.setText(text0);
            text=""+Math.sqrt(val);
            t1.setText(text);
            calflag=true;
    }//GEN-LAST:event_bRutActionPerformed

    private void bFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFacActionPerformed
        text0=""+t1.getText()+"!";
        t0.setText(text0);
        int x=(int)Double.parseDouble(t1.getText());
        text=""+Factorial(x);
        t1.setText(text);
        calflag=true;
    }//GEN-LAST:event_bFacActionPerformed

    private void RadianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadianActionPerformed
        if(!radflag)
        {
            radflag=true;
            Radian.setText("Radian");
        }
        else
        {
            Radian.setText("Degree");
            radflag=false;
        }
    }//GEN-LAST:event_RadianActionPerformed

    private void bIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIntActionPerformed
        val=Double.parseDouble(t1.getText());
        text0="Int("+val+")";
        t0.setText(text0);
        text=""+Math.floor(val);
        t1.setText(text);
        calflag=true;
    }//GEN-LAST:event_bIntActionPerformed

    private void bX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bX3ActionPerformed
        text0="cube("+t1.getText()+")";
        t0.setText(text0);
        val=Double.parseDouble(t1.getText());
        text=""+val*val*val;
        t1.setText(text);
        calflag=true;

    }//GEN-LAST:event_bX3ActionPerformed

    double arr[]=new double[100];
    int i=0;
    boolean memflag=false;
    private void MemPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemPlusActionPerformed
            arr[i++]=Double.parseDouble(t1.getText());
            memflag=true;
    }//GEN-LAST:event_MemPlusActionPerformed

    private void MemMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemMinActionPerformed
        if(arr.length>0){
        arr[arr.length-1]=0;
        memflag=true;
        }
    }//GEN-LAST:event_MemMinActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Help: Coming Soon....:(");

    }//GEN-LAST:event_HelpActionPerformed

    private void ScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScientificActionPerformed
            Radian.setVisible(true);
            bSin.setVisible(true);
            bCos.setVisible(true);
            bRut.setVisible(true);
            bTan.setVisible(true);
            bPi.setVisible(true);
            bX2.setVisible(true);
            bX3.setVisible(true);
            bXY.setVisible(true);
            b10X.setVisible(true);
            bPM.setVisible(true);
            bInt.setVisible(true);
            bFac.setVisible(true);
            setSize(460,310);
            t0.setBackground(Color.WHITE);
            t1.setBackground(Color.WHITE);
    }//GEN-LAST:event_ScientificActionPerformed
            boolean stdflag=false;
    private void StandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardActionPerformed
            Radian.setVisible(false);
            bSin.setVisible(false);
            bCos.setVisible(false);
            bRut.setVisible(false);
            bTan.setVisible(false);
            bPi.setVisible(false);
            bX2.setVisible(false);
            bX3.setVisible(false);
            bXY.setVisible(false);
            b10X.setVisible(false);
            bPM.setVisible(false);
            bInt.setVisible(false);
            bFac.setVisible(false);
            stdflag=true;
            setSize(300,310);
            t0.setBackground(Color.WHITE);
            t1.setBackground(Color.WHITE);
    }//GEN-LAST:event_StandardActionPerformed

    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jFrame j=new jFrame();
                j.setVisible(true);
                j.setTitle("Calculator");
                j.set();
                j.setLocation(350,200);

            }
        });
            
    }
private double  Factorial(int n)
{
    double f=1;
    if(n==0)
        return 1;
    for(int k=n;k>=1;k--)
        f=f*k;
    return f;


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem Help;
    private javax.swing.JButton MemMin;
    private javax.swing.JButton MemPlus;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JToggleButton Radian;
    private javax.swing.JMenuItem Scientific;
    private javax.swing.JMenuItem Standard;
    private javax.swing.JMenuItem Us;
    private javax.swing.JMenu View;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10X;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bBSp;
    private javax.swing.JButton bCos;
    private javax.swing.JButton bDec;
    private javax.swing.JButton bDiv;
    private javax.swing.JButton bEq;
    private javax.swing.JButton bFac;
    private javax.swing.JButton bInt;
    private javax.swing.JButton bMin;
    private javax.swing.JButton bMod;
    private javax.swing.JButton bMul;
    private javax.swing.JButton bPM;
    private javax.swing.JButton bPi;
    private javax.swing.JButton bRut;
    private javax.swing.JButton bSin;
    private javax.swing.JButton bTan;
    private javax.swing.JButton bX2;
    private javax.swing.JButton bX3;
    private javax.swing.JButton bXY;
    private javax.swing.JTextField t0;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}